name: docker-template-ci

on: [push, pull_request]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v1
      - name: Build docker image
        run: docker-compose build
      - name: Test docker image
        run: docker-compose up --exit-code-from hello-docker
